// Generated by CoffeeScript 1.9.2
var app, gems;

app = angular.module('gemStore', []);

app.controller('StoreController', function() {
  this.products = gems;
  return true;
});

gems = [
  {
    name: 'Azurite',
    price: 2.95
  }, {
    name: 'Bloodstone',
    price: 5.95
  }, {
    name: 'Zircon',
    price: 3.95
  }
];
